### ISSUE TITLE
"Dependency is not satisfiable" problem

### ISSUE THREAD

**Issue by Hilyxx** [slimbook/slimbookbattery#10]
**System** 
Ubuntu Xenial 16.04

**Application** 
slimbookbattery_3.7beta

**Issue** 
Slimbook battery can't be installed because **python-ayatana-indicator** and **gnome-shell-extension-appindicator** don't exist.

![Screenshot from 2019-06-07 02 03 52](https://user-images.githubusercontent.com/21991448/59073782-e9459900-88c8-11e9-82db-94b62e5d567a.png)

**Comment by slimbook** [comment]
Solved!
Thanks

**Comment by ju4n-seb4sti4n** [comment]
Hi...same issue
`:~$ sudo apt-get install slimbookbattery
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 slimbookbattery : Depends: gnome-shell-extension-appindicator but it is not installable
E: Unable to correct problems, you have held broken packages.
:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
:~$`

**Comment by slimbook** [comment]
Solved!! 
Try again.
