### ISSUE TITLE
Can we have some option to disable bright changing under advanced mode?

### ISSUE THREAD

**Issue by aquaspy** [slimbook/slimbookbattery#15]
I really really enjoy slimbook battery, but I always control my bright :\ 
I wanted to disable brigh changing under advanced mode but I could only choose how many bright I wanted for each mode. Can we have a disable bright changing option? Thanks!

**Comment by slimbook** [comment]
Hello,
With future versions.
Thanks

**Comment by aquaspy** [comment]
Thanks!! Amazing
