### ISSUE TITLE
Documentation | Prerequisite to installation

### ISSUE THREAD

**Issue by Ricky-Tigg** [slimbook/slimbookbattery#18]
Use-case:  AC adapter kept connected while using a laptop with a Li-ion battery connected.

- Microsoft Windows' side  – _present here as comparison mean_

[ASUS Battery Health Charging](https://www.asus.com/us/support/FAQ/1032726/) software is active and operating as intended. Option applied, _Maximum Lifespan Mode_ here illustrated, acts as follows: _Stops charging when power is above 60 % and resumes charging when power is below 58 %_, thus optimized.

![Windows ASUS_Battery_Health_Charging _interface](https://user-images.githubusercontent.com/26058215/83774395-4fa4f900-a68e-11ea-8a04-387ad939e901.jpg)

- Linux's side  – **non-Ubuntu or derivative**

TLP which role is limited at only maximizing battery runtime thus not minimizing battery wear, is active. The battery is often in a state of high-power, 98.4375–100 % for extended length of time which causes a reduction in battery spanlife. 

-  Investigation regarding Linux  – **Ubuntu or derivative** alone

According to the  _Advanced mode_ section,, _Battery Cycles configuration_ tab of the  [documentation](https://slimbook.es/en/tutoriales/aplicaciones-slimbook/398-slimbook-battery-3-application-for-optimize-battery-of-your-laptop#advanced-mode), Slimbook Battery 3 supports a similar operational mode, be the CPUs AMD or Intel. Can you confirm that?

It is not stated yet whether a procedure may be required to install that application. Is the uninstallation of any other installed power management application  –such as TLP– required previous to the installation of this application?

**Comment by slimbook** [comment]
Good morning Ricky,


Slimbook battery can't stop the charge of the battery, but can notify you when it reaches a certain level to keep the batter wear under control.

Actually, Slimbook Battery relies on TLP at it's core. Slimbook Battery is an easy to use GUI which offers configurable and pre-made presets for user convenience.

The installation of Slimbook Battery will install all its dependencies beforehand. If you already have TLP installed, it should update it to the latest version or if you already have done some configurations on your own, it may cause conflicts with your settings.

Other than that, we are unable to test your actual network interface power draws because we don't have any ASUS computers here.

**Comment by Ricky-Tigg** [comment]
Wise i must have been for seeking such a valuable technical information – this application does not manage the battery wear–. As a consequence i can feel privileged to know it since it is juridically eligible to be mentioned as part of a public documentation. 

A self-explicit statement in the company's official documentation regards to the true nature of this application could be required. Lacking such statement is prone to cause a damage as severe as leading a reader of your current documentation to make an acquisition of a product  –here a SLIMBOOK-branded laptop– upon a presumed existing characteristic that does not exist. That the kind of lack that cannot be ignored indefinitely on Linux's side for any developer seeking to fully manage the behaviors of a Li-ion laptop battery. 

As noticeable none of those SLIMBOOKs are available with AMD processors while those processors are generally in many cases superior regards to performance/consumption/price ratios than Intel's ones which are there singularly present alone. That may have an effect on the capacity to sell mainly to enterprises.

**Comment by slimbook** [comment]
We are working on it.

**Comment by amalcor** [comment]
Hello,
I'm not really familiar with the world of ubuntu and linux, but it seems that with the new kernel 5.4, it added support for blocking the battery charge the same manner as the asus software. With a simple writing in the file /sys/class/power_supply/BAT0/charge_control_end_threshold of the maximum of battery you want to charge to, it makes charging stop on asus laptop and others that support it. You can look at it more precisely : https://wiki.archlinux.org/index.php/ASUS_Zenbook_UX534#Battery_charge_threshold.
I don't really know if we have the possibility to contribute to the project, but I think it would be an interesting feature to add to the software, and I would be interested to try to participate in this even if i'm not an expert.

**Comment by Ricky-Tigg** [comment]
That's a valuable link you brought to that discussion. I confirm the method depicted there to produce the same beneficial effect in Fedora Linux installed on a ASUS X507UA laptop. I do thank you like II rarely have the occasion nowadays.  Arch Linux too deserves my thanks.

In my system the discontinuing charge value was set to **60** . Reported charge value while the machine is plugged to AC network remains constantly at **59**. I lack knowledge to determine if that state is harmful to the battery life expectancy. I guess it might be since it means there is no proper discharge as well. I wish the property 
/sys/class/power_supply/BAT0/_charge_control_begin_threshold_ was existing.
